import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import PostCard from "../components/PostCard";
import { products } from "../data/posts";
export default function Home(){
 const pageSize=12; const [page,setPage]=useState(1); const pageCount=Math.ceil(products.length/pageSize);
 useEffect(()=>{if(page>1)document.querySelector("#featured-products")?.scrollIntoView({behavior:"smooth"})},[page]);
 const visible=products.slice((page-1)*pageSize,page*pageSize);
 return <><section className="hero container"><div className="hero-copy"><p className="eyebrow gold">Curated festive fashion</p><h1>A premium storefront for statement lehenga and occasion wear.</h1><p>women.collection.in Market Place, E-Commerce, Buy new fashion</p><div className="button-row"><a className="button gold-button" href="#featured-products">Explore Collection</a><Link className="button outline-button" to="/about">Our Story</Link></div><div className="hero-facts"><div><span>Style Direction</span><b>Editorial, polished, modern</b></div><div><span>Palette</span><b>Midnight, champagne, ivory</b></div><div><span>Experience</span><b>Premium browsing to checkout</b></div></div></div><div className="hero-art"><img src="/images/hero.png" alt="Premium fashion showcase"/><div><span>Premium storefront refresh</span><p>Designed to feel refined, current, and high-value at first glance.</p></div></div></section>
 <section className="feature-strip container">{[["New visual identity","A more premium first impression","Sharper typography, professional colors, and calmer spacing help the brand look newer and more trustworthy."],["Made for conversion","Clear browsing flow","Product cards, buttons, and category navigation are visually stronger and easier to scan."],["Consistent tone","Premium from start to finish","The same design language carries through product details, cart, information, and checkout."]].map(x=><div key={x[0]}><p className="eyebrow gold">{x[0]}</p><h2>{x[1]}</h2><p>{x[2]}</p></div>)}</section>
 <section id="featured-products" className="collection container"><div className="section-head"><div><p className="eyebrow gold">Featured collection</p><h2>Signature looks with a refined presentation.</h2><p>Explore all {products.length} pieces from the complete catalogue, with elevated card styling and stronger calls to action.</p></div><Link to="/contact">Need styling help? <span>→</span></Link></div><div className="product-grid">{visible.map(p=><PostCard key={p.slug} post={p}/>)}</div><div className="pagination"><button onClick={()=>setPage(Math.max(1,page-1))} disabled={page===1}>« Prev</button>{Array.from({length:pageCount},(_,i)=>i+1).map(x=><button onClick={()=>setPage(x)} className={x===page?"active":""} key={x}>{x}</button>)}<button onClick={()=>setPage(Math.min(pageCount,page+1))} disabled={page===pageCount}>Next »</button></div></section></>
}
